go-json-experiment/json

options.go
Tiny grammar nit/typo. Latter isn't entirely wrong, but usually means the 2nd of two choices, rather than the last of many choices. Contextually `later` is preferred. I think. I'm a software engineer not an editor.
=> Fix latter to later in options.go

README.md
It took me a while to find it again. I expected it to be linked from the README but it was not.
=> README.md: Link to the Github discussion

arshal_test.go, jsontext/decode.go, jsontext/encode.go, jsontext/state.go, jsontext/state_test.go
When processing JSON as a stream, it is conceivable that the total number of elements in a JSON object or array exceeds a 32-bit integer.
Switch from int to int64 for a similar reason as why io.Copy returns int64 instead of int.
Note that the depth still uses an int because the stack must be representable in memory, which is limited to the native integer width of the platform. This is similar to how io.Reader.Read returns an int because the length of a []byte cannot possibly be larger than the largest int.
=> Use int64 for object or array length

jsontext/decode.go
Decoder panic message refers to io.Writer, should be io.Reader
=> Correct decoder panic message

errors.go, jsontext/coder_test.go, jsontext/decode.go, jsontext/decode_test.go, jsontext/encode.go, jsontext/encode_test.go, jsontext/example_test.go, jsontext/pointer.go, jsontext/pointer_test.go, jsontext/state.go
Declare a jsontext.Pointer type as a named string type.
This allows us to implement a Tokens method to conveniently iterate over all the reference tokens in the pointer using the upcoming iterators support.
The new functionally is currently not tested by CI, but can be manually tested with:
GOEXPERIMENT=rangefunc go.tip test ./...
=> Use a concrete type for JSON pointer

arshal_time.go
The cmp.Or helper was added in Go 1.22.
=> Use cmp.Or to select appropriate time.Format format

arshal_default.go, arshal_test.go
Previously, if StringifyNumbers was specified,
we would permit unmarshaling of a JSON number into a Go number. However, this is not how the v1 equivalent functionality operated. In v1, once the `string` tag option was specified, it would only unmarshal a JSON string containing a JSON number, but would reject a JSON number.
It may be reasonable to provide a separate option that allows the more flexible unmarshal behavior that this commit breaks, but that can be a future change. For now, we are working towards implementing v1 entirely in terms of v2.
=> Reject JSON numbers with StringifyNumbers when unmarshaling

arshal_default.go, arshal_test.go, internal/jsonflags/flags.go, options.go
By default, Marshal serializes Go structs with all fields even if each field is the zero Go value.
This can lead to verbose output emitting fields for which it is often indistinguishable from the zero value of the field itself.
The caller-specified OmitZeroStructFields is equivalent to specifying the omitzero tag option on every Go struct field. Static analysis of Go code used with JSON indicates that about 50% of all struct fields have `omitempty` specified. While `omitempty` is not the same as `omitzero`, it is probably safer to provide a caller-scoped OmitZeroStructFields option since doing so is more likely to produce output that is semantically equivalent to if the option was not specified at all.
The exceptions to the above is if the field value contains a -0.0 or if it implements …
=> Implement support for OmitZeroStructFields

arshal_default.go, arshal_test.go, internal/jsonflags/flags.go, v1/options.go
In v1, the `string` tag option would stringify bools and strings. Add an option to support this behavior in v2.
=> Add support for legacy string tag option behavior

arshal_default.go, arshal_test.go, jsontext/coder_test.go, jsontext/decode.go, jsontext/encode.go
Previously, we used to populate the JSON stack pointer only under the semantics of `AllowDuplicateNames(false)`. The argument made at the time was that the stack pointer becomes imprecise if there are duplicate names and that someone might want to disable duplicate name checks for the sake of performance in which case the logic to maintain the name stack becomes an unnecessary burden if the user does not care about ever retrieving the stack.
However, preserving the stack pointer is important for providing good errors and v1 has functionally always operated under `AllowDuplicateNames(true)` semantics. Thus, in order to preserve good errors in v1, always maintain the name stack needed to produce a JSON pointer.
=> Always maintain JSON stack pointer

jsontext/encode.go
By specifying the isVerbatim flag to names.insertQuoted, the method can avoid unquoting the name since it knows that it only needs to strip off the surrounding double quotes.
Performance:
name                                           old speed      new speed      delta
Testdata/CanadaGeometry/Encode/Value/Buffered  1.12GB/s ± 0%  1.15GB/s ± 3%     ~     (p=0.151 n=5+5)
Testdata/CitmCatalog/Encode/Value/Buffered     1.76GB/s ± 0%  1.99GB/s ± 1%  +13.19%  (p=0.008 n=5+5)
Testdata/GolangSource/Encode/Value/Buffered     793MB/s ± 4%   949MB/s ± 1%  +19.68%  (p=0.008 n=5+5)
Testdata/StringEscaped/Encode/Value/Buffered    228MB/s ± 1%   229MB/s ± 0%     ~     (p=0.421 n=5+5)
Testdata/StringUnicode/Encode/Value/Buffered    983MB/s ± 0%  1014MB/s ± 1%   +3.12%  (p=0.008 n=5+5) …
=> Optimize Encoder.WriteValue for object names

jsontext/state.go
In #65, we always populate the JSON pointer stack. Thus, there is no need to use the fallback logic of encoding the missing name with the member index.
=> Assume Names stack is always populated for StackPointer

arshal_any.go, arshal_default.go, arshal_inlined.go, arshal_test.go, errors.go, internal/jsonwire/wire.go, jsontext/coder_test.go, jsontext/decode.go, jsontext/decode_test.go, jsontext/encode.go, jsontext/encode_test.go, jsontext/errors.go, jsontext/export.go, jsontext/fuzz_test.go, jsontext/quote.go, jsontext/state.go, jsontext/state_test.go, jsontext/token.go, jsontext/value_test.go
Make SyntacticError precise about the position of the error by also recording the JSON pointer.
Other changes:
* Make SyntacticError wrap an error.
* Export ErrDuplicateName as a means to programmatically identify a duplicate object name error.
* Export ErrNonStringName to indicate a syntax error when the expected JSON object name is not a string.
* Always wrap io.ErrUnexpectedEOF in SyntacticError.
* Avoid any dependency injection between jsontext and jsonwire.
* Add convenience methods to jsontext.Pointer.
=> Add JSONPointer to SyntacticError

errors.go, internal/jsonwire/wire.go, internal/jsonwire/wire_test.go, jsontext/errors.go
For deeply nested JSON values, the printed JSON pointer could become excessively long for logging. Truncate the pointer and preserve the head and tail of the pointer.
=> Truncate JSON pointer when printing

arshal.go, arshal_any.go, arshal_default.go, arshal_funcs.go, arshal_inlined.go, arshal_methods.go, arshal_test.go, arshal_time.go, errors.go, errors_test.go, example_test.go, fields.go, fields_test.go, fold_test.go, jsontext/decode.go, jsontext/encode.go, jsontext/errors.go, jsontext/export.go, jsontext/state.go, jsontext/state_test.go, jsontext/token.go
Changes made:
* Always populate SemanticError.JSONPointer.
* Export ErrUnknownName to programmatically identify an unknown name.
* Reduce verbosity of SemanticError.Error method.
* Apply Hyrum-proofing on a per-process basis, rather than on a per-error.Error method call.
* Cleanup error wrapping for user-provided method and function calls. Some heuristics were used to provided reasonable position injection into user-provided errors.
=> Improve error positioning of SemanticError

arshal_test.go, errors.go
Every caller of newUnmarshalErrorBefore is for the case where the Go type has some problem and cannot be unmarshaled into. In such a case, recording the upcoming JSON kind is a red herring since it is information that is not directly relevant to the problem.
=> Avoid recording JSON kind in unmarshal errors before next token

fields.go
Use of cmp.Or with a series of compare function is more readable as it clearly which ordering dimension takes precedence.
=> Cleanup field sorting

fields.go, fields_test.go
An inlined type cannot support any of the interfaces with user-defined behavior, otherwise, it is impossible to derive the set of fields handled by the type.
Add the new encoding.TextAppender type to the list.
=> Add encoding.TextAppender to forbidden inline types

arshal_inlined.go, arshal_test.go, doc.go, fields.go, fields_test.go
It should be possible to support map[~string]T as an inlined fallback so long as the string type does not implement marshal/unmarshal methods.
=> Support named strings as inlined map keys

arshal_default.go, internal/jsonflags/flags.go, internal/jsonwire/encode.go, jsontext/value.go, v1/failing.txt, v1/options.go
For doubly escaped strings, the v1 behavior was to apply escaping for EscapeForHTML and EscapeForJS on the first pass, rather than on the second pass. This does lead to unnecessarily longer outputs since escaping on the first pass means that the newly included '\\' characters have to be escaped again in the second pass. Doubly escaped strings are already an esoteric feature of v1, so we should preserve the semantic.
Also, when encoding the raw output of MarshalJSON, the v1 behavior was to preserve any pre-existing escape sequences, while still escaping any characters that might need escaping per EscapeForHTML and EscapeForJS. Replicate this behavior.
=> Implement legacy semantics for string escaping behavior

arshal_default.go, arshal_methods.go, arshal_test.go, arshal_time.go, v1/decode.go, v1/decode_test.go, v1/failing.txt, v1/options.go
This includes a minor v2 change where it is valid to unmarshal a JSON null into an encoding.TextMarshaler.
TestInterfaceSet was modernized and had more test cases added. The behavior that it enforces is identical to what v1 does today. This test change has been upstreamed as https://go.dev/cl/638256.
=> Implement legacy semantics for merging

arshal_default.go, v1/failing.txt, v1/options.go
When the `string` option is used, a JSON null quoted within a JSON string is a valid substitute for a JSON null.
=> Implement legacy support for quoted nulls

arshal_default.go, arshal_test.go
In PR #84, the logic accidentally stopped performing the duplicate name check under the legacy merge semantics, when these are orthogonal concerns.
Push the check down into the body if v2.IsValid.
=> Fix duplicate name check with maps under legacy merging

arshal_default.go, arshal_methods.go, arshal_test.go, internal/jsonflags/flags.go, v1/failing.txt, v1/options.go
The FormatByteArrayAsArray option is renamed to
FormatBytesWithLegacySemantics with increased feature scope.
In v2, the behavior was altered for when a []~byte or [N]~byte is treated as using some form of binary data encoding (RFC 4648). Implement support for prior semantics.
=> Implement legacy support for binary data encoding

v1/decode_test.go
In v1, a special-case check was added for when an interface value contained a pointer to itself, which would lead to an infinite cycle trying to following the sequence until it found a non-interface or non-pointer value.
In particular, it would detect this pattern:
var v any
v = &v
json.Unmarshal(..., v)
However, this does not detect the general problem. Thus, v1 would still run into an infinite cycle with:
var v any
v1 := &v
v = &v1
json.Unmarshal(..., v)
where there are 2 layers of pointers, still leading to a cycle.
We should either detect the general case or
not try to detect cycles at all.
Fundamentally, it is difficult to detect the general case without either O(N) memory or doing something clever like Floyd's cycle finding algorithm. Both approaches are expensive for the …
=> Remove TestUnmarshalRecursivePointer

arshal.go, arshal_default.go
Previously, map[constraints.Integer | constraints.Float]T would marshal the numeric key type by explicitly setting the StringifyNumbers option. Instead, we make it the responsibility of the arshaler to check whether it is serializing for a map key and to use a JSON string representation.
While this is technically a breaking change,
it is highly unlikely that any existing code is affected.
The motivation for this change is to support legacy method calling semantics where json.{Marshaler,Unmarshaler} were not called for map keys.
With the prior approach, we would need an internal "isMapKey" flag that's set by makeMapArshaler to indicate that the current Go type is within the context of a map key.
With the current approach, the logic that …
=> Avoid specifying StringifyNumbers for map keys

arshal_default.go, arshal_methods.go, fields.go
The v2 semantics regarding methods has the consistent property that only one method is ever called for a particular Go type regardless of the calling context.
For example, if T implements both MarshalJSON and MarshalText, then MarshalJSON will always be used and it could very well be the case that MarshalText does not exist.
Unfortunately, v1 does not have this property where sometimes MarshalJSON is called, and othertimes MarshalText is called.
Method calling today is handled using logic like:
switch which := implementsWhich(t, ti1, ti2, ti3); which {
case ti1:
v = ... // expr1
case ti2:
v = ... // expr2
case ti3:
v = ... // expr3
}
where the highest precedence interface case is taken and all other interfaces are ignored (since they can no longer matter). This programming pattern makes …
=> Refactor method handling logic

v1/decode.go
It is not true that Unmarshal "conventionally" treats JSON nulls as a no-op. Rather it is inconsistent about whether it clears the value or is treated as a no-op.
=> Remove inaccurate documentation on Unmarshaler

v1/decode.go
In #91, we no longer specify StringifyNumbers when serializating a map key. Thus, check whether we are marshaling for a JSON object name, and assume stringification.
=> Check whether serializing a JSON object name for Number

arshal.go, arshal_any.go, arshal_default.go, arshal_funcs.go, arshal_inlined.go, arshal_methods.go
Instead of consulting the flags on the coder via:
export.Encoder(enc).Flags
export.Decoder(dec).Flags
consult flags on the call-provided arshal options via:
mo.Flags
uo.Flags
This avoids unnecessarily peaking at the internals flags
of Encoder or Decoder and also allows us to simplify
some flag checking logic.
For example, the following are all equivalent:
export.Encoder(enc).Flags.Get(Foo) || mo.Flags.Get(Bar)
mo.Flags.Get(Foo) || mo.Flags.Get(Bar)
mo.Flags.Get(Foo | Bar)
A similar transform can also be done by applying
De Morgan's law to the following:
!export.Encoder(enc).Flags.Get(Foo) && !mo.Flags.Get(Bar)
!mo.Flags.Get(Foo) && !mo.Flags.Get(Bar)
!!(!mo.Flags.Get(Foo) && !mo.Flags.Get(Bar))
!(mo.Flags.Get(Foo) || mo.Flags.Get(Bar))
!(mo.Flags.Get(Foo | Bar))
!mo.Flags.Get(Foo | Bar) …
=> Use arshal flags instead of coder flags

arshal_default.go, arshal_test.go
As a minor behavior change, we still store the decoded data even if the sizes mismatch. If the input is too large, then the excess is truncated. If the input is too small, then we zero out the remainder. This matches the behavior of how array underflow and overflow are handled
for normal [N]T arrays that are not byte sequences.
=> Use AppendEncode and AppendDecode available in Go 1.22

arshal_test.go, arshal_time.go, internal/jsonflags/flags.go, v1/options.go
Rename FormatTimeDurationAsNanosecond as FormatTimeWithLegacySemantics to cover a wider range of legacy behavior.
In particular, we avoid strict RFC 3339 checks under such a flag. Also, make calling of time.Time behavior mimic how error handling is usually done for other method calls.
=> Avoid strict RFC 3339 checks for time.Time

arshal_test.go, bench_test.go, fold_test.go
Adjust the tests to assist in merging this into the stdlib. In particular:
* In bench_test.go, switch from package json to json_test.
* In structUnexportedEmbeddedMethodTag, embed encodingTextAppender since netip.Addr now supports the AppendText method.
=> Adjust tests for merging into stdlib

migrate.sh
The migrate.sh script takes in a checkout of the Go toolchain and replaces encoding/json with the v2 prototype.
It also mutate some tests to ensure that the toolchain tests all continue to pass.
=> Add migrate.sh

arshal_default.go
A previous commit (PR #91) already removed support for setting StringifyNumbers and made it the responsibility of arshaler to check whether it was serializing for a JSON object name.
This commit removes one place we accidentally still set the flag.
=> Remove setting StringifyNumbers for map keys

internal/jsonflags/flags.go, v1/options.go
WARNING: This contains breaking changes.
This option was merged into ReportErrorsWithLegacySemantics (#109), but the flag was not deleted in that commit.
=> Remove IgnoreStructErrors option

v1/options.go
The entirety of the v1 API already lives in this package.
=> Remove stale v1 docs

arshal_test.go, arshal_time.go
Previously, if StringifyNumbers was specified,
we would permit unmarshaling of a JSON number into a Go number. However, this is not how the v1 equivalent functionality operated. In v1, once the `string` tag option was specified, it would only unmarshal a JSON string containing a JSON number, but would reject a JSON number.
In #60, we made v2 more consistent with v1 for regular numeric types, but forgot to do so for time.Duration as well.
Also, in #91, we no longer specify StringifyNumbers for map keys and expect a type to check the JSON state machine to handle object names specially. Do the same for time.Duration and time.Time.
=> Handle string option for time types similar to other types

arshal_time.go, arshal_time_test.go
Otherwise FormatTime fails on GOARCH=386.
=> Use uint64 in time calculations

arshal.go, arshal_default.go
When operating under the Deterministic option,
sort names according to UTF-8 instead of UTF-16.
The practical difference is negligible,
but the JSONv2 discussion revealed that many
objected to sorted according to UTF-16,
which is what RFC 8785 specifies.
Given that Deterministic does not say we comply with RFC 8785, we can choose any arbitrary ordering.
=> Deterministically sort by UTF-8 instead of UTF-16

arshal_default.go, internal/jsonflags/flags.go, internal/jsonwire/encode.go, jsontext/value.go, migrate.sh, v1/options.go
Combine the EscapeInvalidUTF8 and PreserveRawStrings options as EscapeWithLegacySemantics. Both options were fairly esoteric, so combine them as they do not justify being individual options.
=> Add EscapeWithLegacySemantics

internal/jsonflags/flags.go
In #119, we folded legacy string escaping behavior into the EscapeWithLegacySemantics flag, but forgot to drop PreserveRawString from being specified as part of DefaultOptionsV1.
=> Drop PreserveRawString from DefaultOptionsV1

arshal.go, arshal_default.go, arshal_funcs.go, arshal_methods.go, arshal_test.go, arshal_time.go, bench_test.go, doc.go, example_orderedobject_test.go, example_test.go, fields_test.go, jsontext/decode.go, jsontext/encode.go, migrate.sh, options.go, v1/decode.go, v1/encode.go
While the MarshalJSONV2 and UnmarshalJSONV2 methods are technically the "v2" variants of the methods, we could use the To and From suffix that conveys slightly more information.
For example, consider the following user-defined methods:
func (v MyType) MarshalJSONTo(e *jsontext.Encoder, o json.Options) error
func (v *MyType) UnmarshalJSONFrom(d *jsontext.Decoder, o json.Options) error
In English, this would naturally read as:
* v will marshal JSON to e
* v will unmarshal JSON from d
The use of the To and From suffix matches the pre-existing io.WriterTo and io.ReaderFrom interfaces, which are optimized variants of io.Writer and io.Reader.
Thus, we perform the following renames:
* MarshalerV1 -> Marshaler
* MarshalerV2 -> MarshalerTo
* MarshalJSONV2 -> MarshalJSONTo
* MarshalFuncV1 -> …
=> Rename MarshalJSONV2 and UnmarshalJSONV2 using To and From suffix

arshal_funcs.go, arshal_methods.go
Remove MarshalerV1, MarshalerV2, UnmarshalerV1, UnmarshalerV2, MarshalFuncV1, MarshalFuncV2, UnmarshalFuncV1, UnmarshalFuncV2, and support for MarshalJSONV1 and UnmarshalJSONV2 methods.
These have been replaced by
Marshaler, MarshalerTo, Unmarshaler, UnmarshalerFrom, MarshalFunc, MarshalToFunc, UnmarshalFunc, UnmarshalFromFunc, and new support for MarshalJSONTo and UnmarshalJSONFrom methods.
Of note, there will not necessarily be a static build failure because of the renamed methods. It is the maintainer's responsibility to verify that MarshalJSONV2 and UnmarshalJSONV2 methods are renamed when updating a dependency on this module.
The prior commit contains support for both MarshalJSONV2 and MarshalJSONTo as well as UnmarshalJSONV2 and …
=> Remove renamed Marshal and Unmarshal methods and functions

v1/decode.go, v1/decode_test.go
A Number can parse from a JSON string regardless of whether the `string` option is specified or not.
Note that this makes Number inconsistent with how other numeric types are handled, but we're aiming for preserving legacy behavior rather than what is consistent.
The upstream change to add these tests is in https://go.dev/cl/641416
=> Fix regression with Number parsing behavior

fields.go, fields_test.go
Some existing codebases include struct fields like the following:
type T struct {
F `json:",inline,omitempty"`
}
This is odd since v1 "encoding/json" never supported an `inline` option. This happened to still work in v1 since F is an embedded field.
However, v2 adds explicit support for the `inline` option, but expects specifying it to be sensibly done.
In particular, there is no clear semantic what the combination of both `inline` and `omitempty` means. The `inline` option means that the entirety of all fields in F are promoted to type T (effectively removing F itself as a serializable field). However, the `omitempty` option means that F as a singular field should not be serialized if empty. However, under `inline` semantics F is not up for consideration as a singular field. Thus, …
=> Keep more inline, but non-sensible fields

v1/decode_test.go, v1/stream.go
In v1, the only time dec.err is sticky is for syntactic errors, but unmarshal errors are not preserved.
Thus, perform an explicit ReadValue call that has sticky errors, but return unmarshal errors without any stickiness.
This pulls in https://go.dev/cl/642295 for tests.
=> Fix regression in legacy Decoder.Decode error stickiness

v1/decode_test.go
Revert changes in TestUnmarshalSyntax to exactly match this test upstream in the Go toolchain.
The movement of the x declaration was originally because we did not yet implement legacy merge semantics,
but that is no longer the case today.
=> Fix regression in v1/TestUnmarshalSyntax

arshal_funcs.go, arshal_test.go, example_test.go, migrate.sh
Join better matches exactly what the function does and
is consistent with the existing JoinOptions function.
=> Rename NewMarshalers and NewUnmarshalers using Join prefix

fields.go, fields_test.go
In v2, we report an error if an inlined struct type also has marshal or unmarshal methods. In such a case, it is ambiguous how we are supposed to inline the type. The presence of methods indicates that the type has custom serialization behavior, but inlining seems to suggest that we should serialize the type as a Go struct.
Instead of skipping the field, still add the field to the queue so that we can process the type's fields as if they were JSON serializable.
=> Fix regression with inlined type with methods

bench_test.go, example_orderedobject_test.go, example_test.go, internal/jsonflags/flags.go, internal/jsonwire/encode.go, internal/jsonwire/wire.go, internal/jsonwire/wire_test.go, jsontext/encode.go, jsontext/encode_test.go, jsontext/fuzz_test.go, jsontext/options.go, jsontext/quote.go, jsontext/token.go, jsontext/value.go, jsontext/value_test.go, migrate.sh, v1/indent.go, v1/options.go
Newly inserted API:
* jsonv1.EscapeInvalidUTF8
* jsontext.Value.Format
* jsontext.AppendFormat
* jsontext.PreserveRawStrings
* jsontext.CanonicalizeRawInts
* jsontext.CanonicalizeRawFloats
* jsontext.ReorderRawObjects
Modified API:
* jsontext.Value.IsValid now takes in variadic Options
* jsontext.Value.Compact now takes in variadic Options
* jsontext.Value.Indent now takes in variadic Options
* jsontext.Value.Canonicalize now takes in variadic Options
Removed API:
* jsonv1.EscapeWithLegacySemantics
The rationale for this change is due to the overly restricted nature of the IsValid, Compact, Indent, and Canonicalize methods on Value.
For example:
* IsValid validates strictly according to RFC 7493, but there are cases where a user wants looser …
=> Refactor jsontext formatting APIs

internal/jsonwire/decode.go
Calling `strconv.ParseFloat()` does not allocate now, so the necessity of fast path is reduced. This fast path actually slows down the process when it fails.
If overflows, return infinity as all other libs, don't give surprise to user. Since we now always treat overflow as error, this may not be very important, but still a breaking change.
Simple benchmark for your reference
```golang
func BenchmarkParseFloat_NoPoint(b *testing.B) {
data := []byte("123456789")
for range b.N {
ParseFloat(data, 64)
}
}
func BenchmarkParseFloat_WithPoint(b *testing.B) {
data := []byte("1234567.89")
for range b.N {
ParseFloat(data, 64)
}
}
func BenchmarkParseFloat_Overflow(b *testing.B) {
data := []byte("1e1000")
for range b.N {
ParseFloat(data, 64)
}
}
```
before
```
goos: darwin
goarch: arm64
pkg: …
```
=>  Remove jsonwire.ParseFloat fast path

arshal_default.go, arshal_inlined.go, bench_test.go, fields.go, fields_test.go
In order to index into struct fields, we always did:
v := addressableValue{va.Field(f.index[0]), va.forcedAddr}
if len(f.index) > 1 {
v = v.fieldByIndex(f.index[1:], false)
...
}
but this led to two implicit bounds check for
f.index[0]
f.index[1:]
since the compiler cannot prove that the f.index is a non-empty slice. This also results in implicit calls to runtime.panicIndex even though this can never happen based on how makeStructFields works.
Instead, have makeStructFields precompute an index0 field which contains the initial field indexing that must always happen, and pre-compute the result of f.index[1:].
Thus, the runtime logic never needs to do these computations. This saves on both runtime performance and binary size.
For example, makeStructArshaler.func6 went from 3756 to 3741 …
=> Optimize indexing of struct fields

arshal_default.go, fields.go, fields_test.go
By default, v1 always specifies EscapeForHTML and EscapeForJS, which prevents the optimization where the pre-quoted name is directly copied to the output buffer.
However, a vast majority of names never have characters that need to be escaped, so pre-compute whether escaping is necessary once within makeStructFields and use the precomputed result. Thus, we speed up marshaling on v1, which has taken a hit in performance when going through the v1in2 emulation.
Performance:
name                                       old time/op    new time/op    delta
Testdata/CitmCatalog/Marshal/Concrete      1.03ms ± 0%    0.92ms ± 1%  -10.94%  (p=0.008 n=5+5)
Testdata/GolangSource/Marshal/Concrete     3.55ms ± 1%    3.20ms ± 2%   -9.88%  (p=0.008 n=5+5)
Testdata/TwitterStatus/Marshal/Concrete     721µs ± …
=> Optimize direct copy of field name for v1

arshal_test.go, doc.go, example_test.go, fields.go, fields_test.go, fold_test.go, options.go, v1/diff_test.go, v1/options.go
Instead of specifying `nocase` or `strictcase` tag options, use a single `case` tag option, which is a key-value pair where the value can only be 'ignore' or 'strict'.
This reads more naturally as `case:ignore` or `case:strict` and is more clear that `case:ignore` and `case:strict` are mutually exclusive tag options.
=> Combine `nocase` and `strictcase` tag options under a `case` option

.github/workflows/ci.yml, arshal.go, arshal_default.go, arshal_methods.go, fields_test.go, go.mod, v1/options.go
Also, remove special case for netip.Addr,
which now implements the encoding.TextAppender interface.
=> Use newer encoding.TextAppender interface in Go 1.24

jsontext/state.go
Use individual var declarations instead of a block declaration.
=> Refactor error variables to improve pkgsite clarity

arshal.go, arshal_test.go, internal/jsonopts/options.go, internal/jsonopts/options_test.go
A jsontext.Encoder and jsontext.Decoder could be constructed with semantic options (e.g., json.Deterministic) where such options are ignored for all encode/decode specific operations.
However, allow semantic options to take effect when such an Encoder or Decoder is passed to MarshalEncode or UnmarshalDecode. The semantic option can still be overridden.
One reason for this behavior is for easier migration. For example, this v1 code:
dec := jsonv1.NewDecoder(in)
dec.DisallowUnknownFields()
for {
... := dec.Decode(...)
}
can be migrated as:
dec := jsontext.NewDecoder(in,
json.RejectUnknownMembers(true))
for {
... := json.UnmarshalDecode(dec, ...)
}
Notice that RejectUnknownMembers does not need
to be repeatedly passed to every UnmarshalDecode call because it is implicitly stored on the …
=> Preserve semantic options in Encoder and Decoder

arshal.go, arshal_funcs.go, arshal_methods.go, arshal_test.go, bench_test.go, example_orderedobject_test.go, example_test.go, jsontext/decode.go, jsontext/encode.go, options.go, v1/decode.go
This drops Options as an argument from
the MarshalerTo and UnmarshalerFrom interfaces and the MarshalToFunc and UnmarshalFromFunc functions.
Instead, the options is stored within the
jsontext.Encoder or jsontext.Decoder and
can be retrieved through the Options method.
This simplifies the API for custom marshalers and unmarshalers and makes it impossible to accidentally drop the options when recursively calling json.MarshalEncode or json.UnmarshalDecode from within a custom marshaler or unmarshaler implementation.
Fixes golang/go#71611
=> Drop Options argument from user-declared methods and functions

bench_test.go, internal/jsontest/testdata.go, migrate.sh
Modify the migrate.sh script to pull changes from https://go.googlesource.com/go as the source of truth. Henceforth, all future changes to this module be done in the official Go repository, which now hosts the v2 code under the goexperiment.jsonv2 build tag. This repository will now become a mirror of the upstream Go repository using migrate.sh script.
=> Switch to go.googlesource.com/go as the source of truth

arshal.go, arshal_default.go, arshal_test.go, arshal_time.go, doc.go, internal/jsonflags/flags.go, internal/jsonwire/encode.go, jsontext/doc.go, jsontext/options.go, v1/decode_test.go, v1/diff_test.go, v1/encode.go, v1/options.go, v1/scanner.go, v1/stream.go
The FormatBytesWithLegacySemantics option has been split apart as:
* FormatBytesWithLegacySemantics
* FormatByteArrayAsArray
* ParseBytesWithLooseRFC4648
The FormatTimeWithLegacySemantics option has been split apart as:
* FormatDurationAsNano
* ParseTimeWithLooseRFC3339
The EscapeInvalidUTF8 option has been removed.
* (https://go.dev/cl/685395) encoding/json: decompose legacy options
* (https://go.dev/cl/685195) encoding/json/v2: add security section to doc
* (https://go.dev/cl/687116) encoding/json: remove legacy option to EscapeInvalidUTF8
* (https://go.dev/cl/687115) encoding/json/v2: report wrapped io.ErrUnexpectedEOF
=> Update to 9159cd4ec6b0e9475dc9c71c830035c1c4c13483

arshal.go, arshal_default.go, arshal_test.go, errors.go, internal/internal.go, jsontext/decode.go, jsontext/decode_test.go, jsontext/encode.go, jsontext/encode_test.go, v1/decode.go, v1/decode_test.go, v1/inject.go, v1/stream.go, v1/stream_test.go
* (https://go.dev/cl/681177) encoding/json/jsontext: preserve buffer capacity in Decoder.Reset
* (https://go.dev/cl/690375) encoding/json/jsontext: preserve buffer capacity in Encoder.Reset
* (https://go.dev/cl/689918) encoding/json: reduce error text regressions under goexperiment.jsonv2
* (https://go.dev/cl/689919) encoding/json: fix extra data regression under goexperiment.jsonv2
* (https://go.dev/cl/689516) encoding/json: fix truncated Token error regression in goexperiment.jsonv2
=> Update to c76c3abc5426ab3d183514c834bcd7d6a653ae89

arshal.go, arshal_test.go, v1/indent.go, v1/scanner_test.go
* (https://go.dev/cl/692175) encoding/json/v2: fix UnmarshalDecode regression with EOF
* (https://go.dev/cl/692195) encoding/json: fix Indent trailing whitespace regression in goexperiment.jsonv2
=> Update to 691af6ca28dad9c72e51346fe10c6aaadc3f940b

arshal_any.go, arshal_default.go, arshal_inlined.go, arshal_test.go, arshal_time.go, errors.go
* (https://go.dev/cl/695278) encoding/json/v2: cleanup error constructors
* (https://go.dev/cl/695276) encoding/json/v2: fix incorrect marshaling of NaN in float64 any
* (https://go.dev/cl/695277) encoding/json/v2: fix wrong type with cyclic marshal error in map[string]any
=> Update to 4b1800e47632d52006e3080580e4e60792389759

.github/workflows/ci.yml, alias.go, arshal_funcs.go, arshal_inlined.go, arshal_methods.go, arshal_time.go, errors.go, example_orderedobject_test.go, go.mod, internal/jsonflags/flags.go
* (https://go.dev/cl/701956) encoding/json/v2: document context annotation with SemanticError
* (https://go.dev/cl/701955) encoding/json: use reflect.TypeAssert
* (https://go.dev/cl/701415) encoding/json/internal/jsonflags: fix comment with wrong field name
=> Update to 30686c4cc89e6952ec00846e34016f37d53f31dd
